#!/bin/bash

# Script Name:                  djavan-demo
# Class Name:                   Ops 201
# Author Name:                  Mr. Norris
# Date of latest revision:      2/9/2021
# Purpose:                      to demo



#Declare variables
user=$(whoami)
host=$(hostname)
greeting="My name is $host"
a=$(ifconfig)
#main
greet() {

    echo -e "\nWhat is thy name?: \n"
    read name

#below is some trash, sorry!
    echo -e "\n$greeting\n"
    echo  -e "The acount $user is logged in\n"
    echo -e "$name, and $user should be friends...\n"
   
} 

netinfo() {

echo -e "I will now copy some information to output.txt\n"
rm output.txt
echo "$a" >> output.txt

}
greet
netinfo