#!/bin/bash

# Script Name:                  djavan-demo
# Class Name:                   Ops 201
# Author Name:                  Mr. Norris
# Date of latest revision:      2/9/2021
# Purpose:                      to demo



#Declare variables
user=$(whoami)
host=$(hostname)
greeting="My name is $host"

#main
greet() {

    echo -e "\nWhat is thy name?: \n"
    read name

#echo greeting
    echo -e "\n$greeting\n"
    echo  -e "The acount $user is logged in\n"
    echo -e "$name, and $user should be friends...\n"
    echo -e "I will now copy some information to $1\n"
   
}
#copy netinfo
copy() {
    
    local a=$(ifconfig)
    echo "$a"
    rm output.txt

}

greet "a file"
a="$(copy)"
echo $a >> output.txt
